// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreateCommand implements createCommand operation.
	//
	// Submit a new FFmpeg command for asynchronous processing.
	//
	// POST /v1/commands
	CreateCommand(ctx context.Context, req *CommandRequest) (CreateCommandRes, error)
	// GetCommand implements getCommand operation.
	//
	// Get the status and results of a specific command.
	//
	// GET /v1/commands/{id}
	GetCommand(ctx context.Context, params GetCommandParams) (GetCommandRes, error)
	// GetOpenAPI implements getOpenAPI operation.
	//
	// Returns the OpenAPI 3.1 specification for this API.
	//
	// GET /openapi.json
	GetOpenAPI(ctx context.Context) error
	// HealthCheck implements healthCheck operation.
	//
	// Check if the service is running.
	//
	// GET /health
	HealthCheck(ctx context.Context) (*HealthResponse, error)
	// ListCommands implements listCommands operation.
	//
	// Get a list of all FFmpeg commands with their current status.
	//
	// GET /v1/commands
	ListCommands(ctx context.Context) (*CommandListResponse, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
