// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateCommand implements createCommand operation.
//
// Submit a new FFmpeg command for asynchronous processing.
//
// POST /v1/commands
func (UnimplementedHandler) CreateCommand(ctx context.Context, req *CommandRequest) (r CreateCommandRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCommand implements getCommand operation.
//
// Get the status and results of a specific command.
//
// GET /v1/commands/{id}
func (UnimplementedHandler) GetCommand(ctx context.Context, params GetCommandParams) (r GetCommandRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOpenAPI implements getOpenAPI operation.
//
// Returns the OpenAPI 3.1 specification for this API.
//
// GET /openapi.json
func (UnimplementedHandler) GetOpenAPI(ctx context.Context) error {
	return ht.ErrNotImplemented
}

// HealthCheck implements healthCheck operation.
//
// Check if the service is running.
//
// GET /health
func (UnimplementedHandler) HealthCheck(ctx context.Context) (r *HealthResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// ListCommands implements listCommands operation.
//
// Get a list of all FFmpeg commands with their current status.
//
// GET /v1/commands
func (UnimplementedHandler) ListCommands(ctx context.Context) (r *CommandListResponse, _ error) {
	return r, ht.ErrNotImplemented
}
