// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"net/url"
	"time"

	"github.com/go-faster/errors"
)

// Ref: #/components/schemas/CommandListResponse
type CommandListResponse struct {
	// Array of commands.
	Commands []CommandStatus `json:"commands"`
	// Total number of commands returned.
	Total int `json:"total"`
}

// GetCommands returns the value of Commands.
func (s *CommandListResponse) GetCommands() []CommandStatus {
	return s.Commands
}

// GetTotal returns the value of Total.
func (s *CommandListResponse) GetTotal() int {
	return s.Total
}

// SetCommands sets the value of Commands.
func (s *CommandListResponse) SetCommands(val []CommandStatus) {
	s.Commands = val
}

// SetTotal sets the value of Total.
func (s *CommandListResponse) SetTotal(val int) {
	s.Total = val
}

// Ref: #/components/schemas/CommandRequest
type CommandRequest struct {
	// Map of input file keys to URLs.
	InputFiles OptCommandRequestInputFiles `json:"input_files"`
	// Map of output file keys to filenames.
	OutputFiles CommandRequestOutputFiles `json:"output_files"`
	// Single FFmpeg command with {{placeholders}} for inputs/outputs.
	FfmpegCommand OptString `json:"ffmpeg_command"`
	// Multiple FFmpeg commands to run in sequence.
	FfmpegCommands []string `json:"ffmpeg_commands"`
	// Webhook URL to POST results when complete.
	Webhook OptURI `json:"webhook"`
	// Your custom reference ID for tracking.
	ReferenceID OptString `json:"reference_id"`
}

// GetInputFiles returns the value of InputFiles.
func (s *CommandRequest) GetInputFiles() OptCommandRequestInputFiles {
	return s.InputFiles
}

// GetOutputFiles returns the value of OutputFiles.
func (s *CommandRequest) GetOutputFiles() CommandRequestOutputFiles {
	return s.OutputFiles
}

// GetFfmpegCommand returns the value of FfmpegCommand.
func (s *CommandRequest) GetFfmpegCommand() OptString {
	return s.FfmpegCommand
}

// GetFfmpegCommands returns the value of FfmpegCommands.
func (s *CommandRequest) GetFfmpegCommands() []string {
	return s.FfmpegCommands
}

// GetWebhook returns the value of Webhook.
func (s *CommandRequest) GetWebhook() OptURI {
	return s.Webhook
}

// GetReferenceID returns the value of ReferenceID.
func (s *CommandRequest) GetReferenceID() OptString {
	return s.ReferenceID
}

// SetInputFiles sets the value of InputFiles.
func (s *CommandRequest) SetInputFiles(val OptCommandRequestInputFiles) {
	s.InputFiles = val
}

// SetOutputFiles sets the value of OutputFiles.
func (s *CommandRequest) SetOutputFiles(val CommandRequestOutputFiles) {
	s.OutputFiles = val
}

// SetFfmpegCommand sets the value of FfmpegCommand.
func (s *CommandRequest) SetFfmpegCommand(val OptString) {
	s.FfmpegCommand = val
}

// SetFfmpegCommands sets the value of FfmpegCommands.
func (s *CommandRequest) SetFfmpegCommands(val []string) {
	s.FfmpegCommands = val
}

// SetWebhook sets the value of Webhook.
func (s *CommandRequest) SetWebhook(val OptURI) {
	s.Webhook = val
}

// SetReferenceID sets the value of ReferenceID.
func (s *CommandRequest) SetReferenceID(val OptString) {
	s.ReferenceID = val
}

// Map of input file keys to URLs.
type CommandRequestInputFiles map[string]string

func (s *CommandRequestInputFiles) init() CommandRequestInputFiles {
	m := *s
	if m == nil {
		m = map[string]string{}
		*s = m
	}
	return m
}

// Map of output file keys to filenames.
type CommandRequestOutputFiles map[string]string

func (s *CommandRequestOutputFiles) init() CommandRequestOutputFiles {
	m := *s
	if m == nil {
		m = map[string]string{}
		*s = m
	}
	return m
}

// Ref: #/components/schemas/CommandResponse
type CommandResponse struct {
	// Unique identifier for the command.
	CommandID string `json:"command_id"`
	// Current status of the command.
	Status CommandResponseStatus `json:"status"`
	// Your custom reference ID if provided.
	ReferenceID OptString `json:"reference_id"`
}

// GetCommandID returns the value of CommandID.
func (s *CommandResponse) GetCommandID() string {
	return s.CommandID
}

// GetStatus returns the value of Status.
func (s *CommandResponse) GetStatus() CommandResponseStatus {
	return s.Status
}

// GetReferenceID returns the value of ReferenceID.
func (s *CommandResponse) GetReferenceID() OptString {
	return s.ReferenceID
}

// SetCommandID sets the value of CommandID.
func (s *CommandResponse) SetCommandID(val string) {
	s.CommandID = val
}

// SetStatus sets the value of Status.
func (s *CommandResponse) SetStatus(val CommandResponseStatus) {
	s.Status = val
}

// SetReferenceID sets the value of ReferenceID.
func (s *CommandResponse) SetReferenceID(val OptString) {
	s.ReferenceID = val
}

func (*CommandResponse) createCommandRes() {}

// Current status of the command.
type CommandResponseStatus string

const (
	CommandResponseStatusPENDING    CommandResponseStatus = "PENDING"
	CommandResponseStatusPROCESSING CommandResponseStatus = "PROCESSING"
	CommandResponseStatusSUCCESS    CommandResponseStatus = "SUCCESS"
	CommandResponseStatusFAILED     CommandResponseStatus = "FAILED"
	CommandResponseStatusRETRYING   CommandResponseStatus = "RETRYING"
)

// AllValues returns all CommandResponseStatus values.
func (CommandResponseStatus) AllValues() []CommandResponseStatus {
	return []CommandResponseStatus{
		CommandResponseStatusPENDING,
		CommandResponseStatusPROCESSING,
		CommandResponseStatusSUCCESS,
		CommandResponseStatusFAILED,
		CommandResponseStatusRETRYING,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s CommandResponseStatus) MarshalText() ([]byte, error) {
	switch s {
	case CommandResponseStatusPENDING:
		return []byte(s), nil
	case CommandResponseStatusPROCESSING:
		return []byte(s), nil
	case CommandResponseStatusSUCCESS:
		return []byte(s), nil
	case CommandResponseStatusFAILED:
		return []byte(s), nil
	case CommandResponseStatusRETRYING:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *CommandResponseStatus) UnmarshalText(data []byte) error {
	switch CommandResponseStatus(data) {
	case CommandResponseStatusPENDING:
		*s = CommandResponseStatusPENDING
		return nil
	case CommandResponseStatusPROCESSING:
		*s = CommandResponseStatusPROCESSING
		return nil
	case CommandResponseStatusSUCCESS:
		*s = CommandResponseStatusSUCCESS
		return nil
	case CommandResponseStatusFAILED:
		*s = CommandResponseStatusFAILED
		return nil
	case CommandResponseStatusRETRYING:
		*s = CommandResponseStatusRETRYING
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/CommandStatus
type CommandStatus struct {
	// Unique identifier for the command.
	CommandID string `json:"command_id"`
	// Current status of the command.
	Status CommandStatusStatus `json:"status"`
	// Map of output files with their metadata.
	OutputFiles     OptCommandStatusOutputFiles `json:"output_files"`
	OriginalRequest OptCommandRequest           `json:"original_request"`
	// Time spent running FFmpeg commands.
	FfmpegCommandRunSeconds OptFloat64 `json:"ffmpeg_command_run_seconds"`
	// Total processing time including downloads.
	TotalProcessingSeconds OptFloat64 `json:"total_processing_seconds"`
	// Error message if command failed.
	Error OptString `json:"error"`
	// When the command was created.
	CreatedAt time.Time `json:"created_at"`
	// When the command completed.
	CompletedAt OptDateTime `json:"completed_at"`
}

// GetCommandID returns the value of CommandID.
func (s *CommandStatus) GetCommandID() string {
	return s.CommandID
}

// GetStatus returns the value of Status.
func (s *CommandStatus) GetStatus() CommandStatusStatus {
	return s.Status
}

// GetOutputFiles returns the value of OutputFiles.
func (s *CommandStatus) GetOutputFiles() OptCommandStatusOutputFiles {
	return s.OutputFiles
}

// GetOriginalRequest returns the value of OriginalRequest.
func (s *CommandStatus) GetOriginalRequest() OptCommandRequest {
	return s.OriginalRequest
}

// GetFfmpegCommandRunSeconds returns the value of FfmpegCommandRunSeconds.
func (s *CommandStatus) GetFfmpegCommandRunSeconds() OptFloat64 {
	return s.FfmpegCommandRunSeconds
}

// GetTotalProcessingSeconds returns the value of TotalProcessingSeconds.
func (s *CommandStatus) GetTotalProcessingSeconds() OptFloat64 {
	return s.TotalProcessingSeconds
}

// GetError returns the value of Error.
func (s *CommandStatus) GetError() OptString {
	return s.Error
}

// GetCreatedAt returns the value of CreatedAt.
func (s *CommandStatus) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetCompletedAt returns the value of CompletedAt.
func (s *CommandStatus) GetCompletedAt() OptDateTime {
	return s.CompletedAt
}

// SetCommandID sets the value of CommandID.
func (s *CommandStatus) SetCommandID(val string) {
	s.CommandID = val
}

// SetStatus sets the value of Status.
func (s *CommandStatus) SetStatus(val CommandStatusStatus) {
	s.Status = val
}

// SetOutputFiles sets the value of OutputFiles.
func (s *CommandStatus) SetOutputFiles(val OptCommandStatusOutputFiles) {
	s.OutputFiles = val
}

// SetOriginalRequest sets the value of OriginalRequest.
func (s *CommandStatus) SetOriginalRequest(val OptCommandRequest) {
	s.OriginalRequest = val
}

// SetFfmpegCommandRunSeconds sets the value of FfmpegCommandRunSeconds.
func (s *CommandStatus) SetFfmpegCommandRunSeconds(val OptFloat64) {
	s.FfmpegCommandRunSeconds = val
}

// SetTotalProcessingSeconds sets the value of TotalProcessingSeconds.
func (s *CommandStatus) SetTotalProcessingSeconds(val OptFloat64) {
	s.TotalProcessingSeconds = val
}

// SetError sets the value of Error.
func (s *CommandStatus) SetError(val OptString) {
	s.Error = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *CommandStatus) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetCompletedAt sets the value of CompletedAt.
func (s *CommandStatus) SetCompletedAt(val OptDateTime) {
	s.CompletedAt = val
}

func (*CommandStatus) getCommandRes() {}

// Map of output files with their metadata.
type CommandStatusOutputFiles map[string]OutputFileInfo

func (s *CommandStatusOutputFiles) init() CommandStatusOutputFiles {
	m := *s
	if m == nil {
		m = map[string]OutputFileInfo{}
		*s = m
	}
	return m
}

// Current status of the command.
type CommandStatusStatus string

const (
	CommandStatusStatusPENDING    CommandStatusStatus = "PENDING"
	CommandStatusStatusPROCESSING CommandStatusStatus = "PROCESSING"
	CommandStatusStatusSUCCESS    CommandStatusStatus = "SUCCESS"
	CommandStatusStatusFAILED     CommandStatusStatus = "FAILED"
	CommandStatusStatusRETRYING   CommandStatusStatus = "RETRYING"
)

// AllValues returns all CommandStatusStatus values.
func (CommandStatusStatus) AllValues() []CommandStatusStatus {
	return []CommandStatusStatus{
		CommandStatusStatusPENDING,
		CommandStatusStatusPROCESSING,
		CommandStatusStatusSUCCESS,
		CommandStatusStatusFAILED,
		CommandStatusStatusRETRYING,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s CommandStatusStatus) MarshalText() ([]byte, error) {
	switch s {
	case CommandStatusStatusPENDING:
		return []byte(s), nil
	case CommandStatusStatusPROCESSING:
		return []byte(s), nil
	case CommandStatusStatusSUCCESS:
		return []byte(s), nil
	case CommandStatusStatusFAILED:
		return []byte(s), nil
	case CommandStatusStatusRETRYING:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *CommandStatusStatus) UnmarshalText(data []byte) error {
	switch CommandStatusStatus(data) {
	case CommandStatusStatusPENDING:
		*s = CommandStatusStatusPENDING
		return nil
	case CommandStatusStatusPROCESSING:
		*s = CommandStatusStatusPROCESSING
		return nil
	case CommandStatusStatusSUCCESS:
		*s = CommandStatusStatusSUCCESS
		return nil
	case CommandStatusStatusFAILED:
		*s = CommandStatusStatusFAILED
		return nil
	case CommandStatusStatusRETRYING:
		*s = CommandStatusStatusRETRYING
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type CreateCommandBadRequest ErrorResponse

func (*CreateCommandBadRequest) createCommandRes() {}

type CreateCommandInternalServerError ErrorResponse

func (*CreateCommandInternalServerError) createCommandRes() {}

// Ref: #/components/schemas/ErrorResponse
type ErrorResponse struct {
	// Error message.
	Error string `json:"error"`
}

// GetError returns the value of Error.
func (s *ErrorResponse) GetError() string {
	return s.Error
}

// SetError sets the value of Error.
func (s *ErrorResponse) SetError(val string) {
	s.Error = val
}

type GetCommandBadRequest ErrorResponse

func (*GetCommandBadRequest) getCommandRes() {}

type GetCommandNotFound ErrorResponse

func (*GetCommandNotFound) getCommandRes() {}

type GetOpenAPIOK struct{}

// Ref: #/components/schemas/HealthResponse
type HealthResponse struct {
	// Status of the service.
	Status string `json:"status"`
}

// GetStatus returns the value of Status.
func (s *HealthResponse) GetStatus() string {
	return s.Status
}

// SetStatus sets the value of Status.
func (s *HealthResponse) SetStatus(val string) {
	s.Status = val
}

// NewOptCommandRequest returns new OptCommandRequest with value set to v.
func NewOptCommandRequest(v CommandRequest) OptCommandRequest {
	return OptCommandRequest{
		Value: v,
		Set:   true,
	}
}

// OptCommandRequest is optional CommandRequest.
type OptCommandRequest struct {
	Value CommandRequest
	Set   bool
}

// IsSet returns true if OptCommandRequest was set.
func (o OptCommandRequest) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCommandRequest) Reset() {
	var v CommandRequest
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCommandRequest) SetTo(v CommandRequest) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCommandRequest) Get() (v CommandRequest, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCommandRequest) Or(d CommandRequest) CommandRequest {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptCommandRequestInputFiles returns new OptCommandRequestInputFiles with value set to v.
func NewOptCommandRequestInputFiles(v CommandRequestInputFiles) OptCommandRequestInputFiles {
	return OptCommandRequestInputFiles{
		Value: v,
		Set:   true,
	}
}

// OptCommandRequestInputFiles is optional CommandRequestInputFiles.
type OptCommandRequestInputFiles struct {
	Value CommandRequestInputFiles
	Set   bool
}

// IsSet returns true if OptCommandRequestInputFiles was set.
func (o OptCommandRequestInputFiles) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCommandRequestInputFiles) Reset() {
	var v CommandRequestInputFiles
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCommandRequestInputFiles) SetTo(v CommandRequestInputFiles) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCommandRequestInputFiles) Get() (v CommandRequestInputFiles, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCommandRequestInputFiles) Or(d CommandRequestInputFiles) CommandRequestInputFiles {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptCommandStatusOutputFiles returns new OptCommandStatusOutputFiles with value set to v.
func NewOptCommandStatusOutputFiles(v CommandStatusOutputFiles) OptCommandStatusOutputFiles {
	return OptCommandStatusOutputFiles{
		Value: v,
		Set:   true,
	}
}

// OptCommandStatusOutputFiles is optional CommandStatusOutputFiles.
type OptCommandStatusOutputFiles struct {
	Value CommandStatusOutputFiles
	Set   bool
}

// IsSet returns true if OptCommandStatusOutputFiles was set.
func (o OptCommandStatusOutputFiles) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCommandStatusOutputFiles) Reset() {
	var v CommandStatusOutputFiles
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCommandStatusOutputFiles) SetTo(v CommandStatusOutputFiles) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCommandStatusOutputFiles) Get() (v CommandStatusOutputFiles, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCommandStatusOutputFiles) Or(d CommandStatusOutputFiles) CommandStatusOutputFiles {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptDateTime returns new OptDateTime with value set to v.
func NewOptDateTime(v time.Time) OptDateTime {
	return OptDateTime{
		Value: v,
		Set:   true,
	}
}

// OptDateTime is optional time.Time.
type OptDateTime struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDateTime was set.
func (o OptDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDateTime) Get() (v time.Time, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptFloat64 returns new OptFloat64 with value set to v.
func NewOptFloat64(v float64) OptFloat64 {
	return OptFloat64{
		Value: v,
		Set:   true,
	}
}

// OptFloat64 is optional float64.
type OptFloat64 struct {
	Value float64
	Set   bool
}

// IsSet returns true if OptFloat64 was set.
func (o OptFloat64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptFloat64) Reset() {
	var v float64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptFloat64) SetTo(v float64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptFloat64) Get() (v float64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptFloat64) Or(d float64) float64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptURI returns new OptURI with value set to v.
func NewOptURI(v url.URL) OptURI {
	return OptURI{
		Value: v,
		Set:   true,
	}
}

// OptURI is optional url.URL.
type OptURI struct {
	Value url.URL
	Set   bool
}

// IsSet returns true if OptURI was set.
func (o OptURI) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptURI) Reset() {
	var v url.URL
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptURI) SetTo(v url.URL) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptURI) Get() (v url.URL, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptURI) Or(d url.URL) url.URL {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/OutputFileInfo
type OutputFileInfo struct {
	// Unique identifier for this output file.
	FileID string `json:"file_id"`
	// File size in megabytes.
	SizeMbytes float64 `json:"size_mbytes"`
	// Type of file.
	FileType OutputFileInfoFileType `json:"file_type"`
	// File extension/format.
	FileFormat string `json:"file_format"`
	// URL or path to access the file.
	StorageURL string `json:"storage_url"`
	// Width in pixels (for images/videos).
	Width OptInt `json:"width"`
	// Height in pixels (for images/videos).
	Height OptInt `json:"height"`
}

// GetFileID returns the value of FileID.
func (s *OutputFileInfo) GetFileID() string {
	return s.FileID
}

// GetSizeMbytes returns the value of SizeMbytes.
func (s *OutputFileInfo) GetSizeMbytes() float64 {
	return s.SizeMbytes
}

// GetFileType returns the value of FileType.
func (s *OutputFileInfo) GetFileType() OutputFileInfoFileType {
	return s.FileType
}

// GetFileFormat returns the value of FileFormat.
func (s *OutputFileInfo) GetFileFormat() string {
	return s.FileFormat
}

// GetStorageURL returns the value of StorageURL.
func (s *OutputFileInfo) GetStorageURL() string {
	return s.StorageURL
}

// GetWidth returns the value of Width.
func (s *OutputFileInfo) GetWidth() OptInt {
	return s.Width
}

// GetHeight returns the value of Height.
func (s *OutputFileInfo) GetHeight() OptInt {
	return s.Height
}

// SetFileID sets the value of FileID.
func (s *OutputFileInfo) SetFileID(val string) {
	s.FileID = val
}

// SetSizeMbytes sets the value of SizeMbytes.
func (s *OutputFileInfo) SetSizeMbytes(val float64) {
	s.SizeMbytes = val
}

// SetFileType sets the value of FileType.
func (s *OutputFileInfo) SetFileType(val OutputFileInfoFileType) {
	s.FileType = val
}

// SetFileFormat sets the value of FileFormat.
func (s *OutputFileInfo) SetFileFormat(val string) {
	s.FileFormat = val
}

// SetStorageURL sets the value of StorageURL.
func (s *OutputFileInfo) SetStorageURL(val string) {
	s.StorageURL = val
}

// SetWidth sets the value of Width.
func (s *OutputFileInfo) SetWidth(val OptInt) {
	s.Width = val
}

// SetHeight sets the value of Height.
func (s *OutputFileInfo) SetHeight(val OptInt) {
	s.Height = val
}

// Type of file.
type OutputFileInfoFileType string

const (
	OutputFileInfoFileTypeImage    OutputFileInfoFileType = "image"
	OutputFileInfoFileTypeVideo    OutputFileInfoFileType = "video"
	OutputFileInfoFileTypeAudio    OutputFileInfoFileType = "audio"
	OutputFileInfoFileTypeSubtitle OutputFileInfoFileType = "subtitle"
	OutputFileInfoFileTypeFile     OutputFileInfoFileType = "file"
)

// AllValues returns all OutputFileInfoFileType values.
func (OutputFileInfoFileType) AllValues() []OutputFileInfoFileType {
	return []OutputFileInfoFileType{
		OutputFileInfoFileTypeImage,
		OutputFileInfoFileTypeVideo,
		OutputFileInfoFileTypeAudio,
		OutputFileInfoFileTypeSubtitle,
		OutputFileInfoFileTypeFile,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s OutputFileInfoFileType) MarshalText() ([]byte, error) {
	switch s {
	case OutputFileInfoFileTypeImage:
		return []byte(s), nil
	case OutputFileInfoFileTypeVideo:
		return []byte(s), nil
	case OutputFileInfoFileTypeAudio:
		return []byte(s), nil
	case OutputFileInfoFileTypeSubtitle:
		return []byte(s), nil
	case OutputFileInfoFileTypeFile:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *OutputFileInfoFileType) UnmarshalText(data []byte) error {
	switch OutputFileInfoFileType(data) {
	case OutputFileInfoFileTypeImage:
		*s = OutputFileInfoFileTypeImage
		return nil
	case OutputFileInfoFileTypeVideo:
		*s = OutputFileInfoFileTypeVideo
		return nil
	case OutputFileInfoFileTypeAudio:
		*s = OutputFileInfoFileTypeAudio
		return nil
	case OutputFileInfoFileTypeSubtitle:
		*s = OutputFileInfoFileTypeSubtitle
		return nil
	case OutputFileInfoFileTypeFile:
		*s = OutputFileInfoFileTypeFile
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}
