// Code generated by ogen, DO NOT EDIT.

package oas

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateCommandOperation OperationName = "CreateCommand"
	GetCommandOperation    OperationName = "GetCommand"
	GetOpenAPIOperation    OperationName = "GetOpenAPI"
	HealthCheckOperation   OperationName = "HealthCheck"
	ListCommandsOperation  OperationName = "ListCommands"
)
